version: "3"

networks:
  traefik_traefik-network:
    external: true

services:
  website:
    image: website:latest
    container_name: website
    build: .
    networks:
      - traefik_traefik-network
    labels:
      - traefik.http.routers.website.rule=Host(`jake.runyan.dev`)
      - traefik.http.routers.website.tls=true
      - traefik.http.routers.website.tls.certresolver=lets-encrypt
      - traefik.http.services.website.loadbalancer.server.port=3000
      - traefik.port=3002