/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  aboutSidebar: [
    {
      type: 'doc',
      label: 'About Me',
      id: 'about/about-me'
    },
  ],

  resumeSidebar: [
    {
      type: 'doc',
      label: 'Resume',
      id: 'resume/resume'
    }
  ],
};

export default sidebars;
